# Generated by Django 3.0.7 on 2020-10-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
