# Generated by Django 3.0.6 on 2020-05-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('game_slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('game_banner', models.ImageField(upload_to='')),
                ('game_name', models.CharField(max_length=255)),
                ('player_name', models.CharField(max_length=255)),
                ('player_score', models.BigIntegerField()),
            ],
        ),
    ]
