# Generated by Django 3.0.6 on 2020-05-24 13:44

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game_banner',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
